name: infra-manga-library
networks:
  mangaLib_net:
    driver: bridge

services:
  mongo:
    container_name: manga-mongo
    image: mongo:7
    command: ["--bind_ip_all", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: manga-lib
    volumes: ["./mongo/data:/data/db"]
    networks: [mangaLib_net]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "admin",
          "--password",
          "admin",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    container_name: manga-worker
    image: nightwolfff/manga-dev:worker
    command: ["python", "main.py"]

    environment:
      MONGO_URI: "mongodb://admin:admin@mongo:27017/manga-lib?authSource=admin"
    depends_on:
      mongo:
        condition: service_healthy
    networks: [mangaLib_net]
    restart: unless-stopped

  server:
    container_name: manga-server
    # build: ./server
    image: nightwolfff/manga-dev:server
    command: ["npm", "run", "dev"]
    env_file:
      - .env.prod
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mangaLib_net

    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: manga-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
    depends_on:
      - server
    networks:
      - mangaLib_net
    restart: unless-stopped
